from .supports import SUPPORT_GENERATORS, get_support_module_name
from .drawer import generate_drawer


def assemble(config) -> str:
    """Generate complete OpenSCAD code from a CabinetConfig."""
    c = config
    parametric = c.output_mode == "parametric"
    parts: list[str] = []

    total_drawers = c.drawers_x * c.drawers_y

    if c.drawer_sizes is None or len(c.drawer_sizes) != total_drawers:
        c.drawer_sizes = [1.0 / total_drawers] * total_drawers

    if parametric:
        parts.append(_parametric_header(c))

    # Support pattern module
    support_gen = SUPPORT_GENERATORS[c.support_type]
    if c.support_type == "honeycomb":
        parts.append(support_gen(0, 0, 0))
    else:
        parts.append(support_gen(0, 0, 0))

    # Drawer module
    parts.append(generate_drawer(0, 0, 0, 0, 0, parametric=True))

    # Cabinet shell
    parts.append(_cabinet_shell(c, parametric))

    # Drawer layout
    parts.append(_drawer_layout(c, parametric))

    # Main assembly
    parts.append(_main_module(c, parametric))

    return "\n\n".join(parts) + "\n"


def _parametric_header(c) -> str:
    return f"""// StorageMaker - Parametric Drawer Cabinet
// Generated by StorageMaker

// --- Parameters ---
width = {c.width};
height = {c.height};
depth = {c.depth};
wall = {c.wall_thickness};
drawers_x = {c.drawers_x};
drawers_y = {c.drawers_y};
clearance = {c.drawer_clearance};
support_t = {c.support_thickness};
back_panel = {"true" if c.back_panel else "false"};

module_name = "{get_support_module_name(c.support_type)}";"""


def _cabinet_shell(c, parametric: bool) -> str:
    if parametric:
        return """module cabinet_shell() {
  union() {
    cube([width, wall, depth]);
    translate([0, height - wall, 0])
      cube([width, wall, depth]);
    translate([0, wall, 0])
      cube([wall, height - 2 * wall, depth]);
    translate([width - wall, wall, 0])
      cube([wall, height - 2 * wall, depth]);
  }
}"""
    else:
        w, h, d, wall = c.width, c.height, c.depth, c.wall_thickness
        return f"""module cabinet_shell() {{
  union() {{
    cube([{w}, {wall}, {d}]);
    translate([0, {h - wall}, 0])
      cube([{w}, {wall}, {d}]);
    translate([0, {wall}, 0])
      cube([{wall}, {h - 2 * wall}, {d}]);
    translate([{w - wall}, {wall}, 0])
      cube([{wall}, {h - 2 * wall}, {d}]);
  }}
}}"""


def _drawer_layout(c, parametric: bool) -> str:
    if parametric:
        return """module drawer_layout() {
  cell_w = (width - 2 * wall - (drawers_x + 1) * clearance) / drawers_x;
  cell_h = (height - 2 * wall - (drawers_y + 1) * clearance) / drawers_y;
  drawer_d = depth - clearance - (back_panel ? wall : 0);
  for (ix = [0 : drawers_x - 1]) {
    for (iy = [0 : drawers_y - 1]) {
      x = wall + clearance + ix * (cell_w + clearance);
      y = wall + clearance + iy * (cell_h + clearance);
      translate([x, y, clearance])
        cube([cell_w, cell_h, drawer_d]);
    }
  }
}"""
    else:
        w, h, d, wall = c.width, c.height, c.depth, c.wall_thickness
        cl = c.drawer_clearance
        dx, dy = c.drawers_x, c.drawers_y
        cell_w = (w - 2 * wall - (dx + 1) * cl) / dx
        cell_h = (h - 2 * wall - (dy + 1) * cl) / dy
        drawer_d = d - cl - (wall if c.back_panel else 0)
        return f"""module drawer_layout() {{
  for (ix = [0 : {dx - 1}]) {{
    for (iy = [0 : {dy - 1}]) {{
      x = {wall} + {cl} + ix * ({cell_w} + {cl});
      y = {wall} + {cl} + iy * ({cell_h} + {cl});
      translate([x, y, {cl}])
        cube([{cell_w}, {cell_h}, {drawer_d}]);
    }}
  }}
}}"""


def _main_module(c, parametric: bool) -> str:
    back_str = ""
    if c.back_panel:
        if parametric:
            back_str = """
  if (back_panel)
    translate([wall, wall, depth - wall])
      cube([width - 2 * wall, height - 2 * wall, wall]);"""
        else:
            w = c.width - 2 * c.wall_thickness
            h = c.height - 2 * c.wall_thickness
            back_str = f"""
  translate([{c.wall_thickness}, {c.wall_thickness}, {c.depth - c.wall_thickness}])
    cube([{w}, {h}, {c.wall_thickness}]);"""

    if parametric:
        return f"""module cabinet() {{
  color("Wheat") cabinet_shell();{back_str}
  color("Tan") drawer_layout();
}}

cabinet();"""
    else:
        return f"""module cabinet() {{
  color("Wheat") cabinet_shell();{back_str}
  color("Tan") drawer_layout();
}}

cabinet();"""
