def assemble_insert(config) -> str:
    c = config
    parametric = c.output_mode == "parametric"
    if parametric:
        return _parametric_insert(c)
    return _resolved_insert(c)


def _parametric_insert(c) -> str:
    return f"""// StorageMaker - Drawer Insert
// Generated by StorageMaker

cabinet_width = {c.cabinet_width};
cabinet_height = {c.cabinet_height};
cabinet_depth = {c.cabinet_depth};
cabinet_wall = {c.cabinet_wall_thickness};
drawers_x = {c.drawers_x};
drawers_y = {c.drawers_y};
drawer_clearance = {c.drawer_clearance};
back_panel = {"true" if c.back_panel else "false"};
fit_clearance = {c.fit_clearance};
insert_wall = {c.insert_wall_thickness};
floor_thickness = {c.floor_thickness};
compartments_x = {c.compartments_x};
compartments_y = {c.compartments_y};

section_width = cabinet_width / drawers_x;
section_height = cabinet_height / drawers_y;
section_depth = cabinet_depth;

insert_width = max(section_width - fit_clearance, insert_wall * 2 + 1);
insert_height = max(section_height - fit_clearance, insert_wall * 2 + 1);
insert_depth = max(section_depth - fit_clearance, floor_thickness + 1);

module drawer_insert() {{
  difference() {{
    cube([insert_width, insert_height, insert_depth]);
    translate([insert_wall, insert_wall, floor_thickness])
      cube([
        insert_width - 2 * insert_wall,
        insert_height - 2 * insert_wall,
        insert_depth - floor_thickness + 1
      ]);
  }}

  if (compartments_x > 1) {{
    divider_span_y = insert_height - 2 * insert_wall;
    divider_z = max(insert_depth - floor_thickness, 1);
    cell_width = (insert_width - 2 * insert_wall) / compartments_x;
    for (ix = [1 : compartments_x - 1]) {{
      translate([insert_wall + ix * cell_width - insert_wall / 2, insert_wall, floor_thickness])
        cube([insert_wall, divider_span_y, divider_z]);
    }}
  }}

  if (compartments_y > 1) {{
    divider_span_x = insert_width - 2 * insert_wall;
    divider_z = max(insert_depth - floor_thickness, 1);
    cell_height = (insert_height - 2 * insert_wall) / compartments_y;
    for (iy = [1 : compartments_y - 1]) {{
      translate([insert_wall, insert_wall + iy * cell_height - insert_wall / 2, floor_thickness])
        cube([divider_span_x, insert_wall, divider_z]);
    }}
  }}
}}

drawer_insert();
"""


def _resolved_insert(c) -> str:
    section_width = _safe_dimension(c.cabinet_width / c.drawers_x, 1)
    section_height = _safe_dimension(c.cabinet_height / c.drawers_y, 1)
    section_depth = _safe_dimension(c.cabinet_depth, 1)
    insert_width = _safe_dimension(
        section_width - c.fit_clearance,
        c.insert_wall_thickness * 2 + 1,
    )
    insert_height = _safe_dimension(
        section_height - c.fit_clearance,
        c.insert_wall_thickness * 2 + 1,
    )
    insert_depth = _safe_dimension(
        section_depth - c.fit_clearance,
        c.floor_thickness + 1,
    )
    inner_width = _safe_dimension(insert_width - 2 * c.insert_wall_thickness, 1)
    inner_height = _safe_dimension(insert_height - 2 * c.insert_wall_thickness, 1)
    divider_height = _safe_dimension(insert_depth - c.floor_thickness, 1)
    cell_width = inner_width / c.compartments_x
    cell_height = inner_height / c.compartments_y

    divider_blocks: list[str] = []
    for index in range(1, c.compartments_x):
        x_pos = c.insert_wall_thickness + index * cell_width - c.insert_wall_thickness / 2
        divider_blocks.append(
            f"""  translate([{x_pos}, {c.insert_wall_thickness}, {c.floor_thickness}])
    cube([{c.insert_wall_thickness}, {inner_height}, {divider_height}]);"""
        )
    for index in range(1, c.compartments_y):
        y_pos = c.insert_wall_thickness + index * cell_height - c.insert_wall_thickness / 2
        divider_blocks.append(
            f"""  translate([{c.insert_wall_thickness}, {y_pos}, {c.floor_thickness}])
    cube([{inner_width}, {c.insert_wall_thickness}, {divider_height}]);"""
        )
    dividers = "\n".join(divider_blocks)

    return f"""// StorageMaker - Drawer Insert
// Generated by StorageMaker

module drawer_insert() {{
  difference() {{
    cube([{insert_width}, {insert_height}, {insert_depth}]);
    translate([{c.insert_wall_thickness}, {c.insert_wall_thickness}, {c.floor_thickness}])
      cube([{inner_width}, {inner_height}, {insert_depth - c.floor_thickness + 1}]);
  }}
{dividers}
}}

drawer_insert();
"""


def _safe_dimension(value: float, minimum: float) -> float:
    return max(value, minimum)