def assemble_insert(config) -> str:
    """Generate OpenSCAD for a drawer insert sized to one cabinet drawer section."""
    c = config
    parametric = c.output_mode == "parametric"
    if parametric:
        return _parametric_insert(c)
    return _resolved_insert(c)


def _parametric_insert(c) -> str:
    return f"""// StorageMaker - Drawer Insert
// Generated by StorageMaker

cabinet_width = {c.cabinet_width};
cabinet_height = {c.cabinet_height};
cabinet_depth = {c.cabinet_depth};
cabinet_wall = {c.cabinet_wall_thickness};
drawers_x = {c.drawers_x};
drawers_y = {c.drawers_y};
drawer_clearance = {c.drawer_clearance};
back_panel = {"true" if c.back_panel else "false"};
fit_clearance = {c.fit_clearance};
insert_wall = {c.insert_wall_thickness};
floor_thickness = {c.floor_thickness};

section_width = cabinet_width / drawers_x;
section_height = cabinet_height / drawers_y;
section_depth = cabinet_depth;

insert_width = max(section_width - fit_clearance, insert_wall * 2 + 1);
insert_height = max(section_height - fit_clearance, insert_wall * 2 + 1);
insert_depth = max(section_depth - fit_clearance, floor_thickness + 1);

module drawer_insert() {{
  difference() {{
    cube([insert_width, insert_depth, insert_height]);
    translate([insert_wall, insert_wall, floor_thickness])
      cube([
        insert_width - 2 * insert_wall,
        insert_depth - 2 * insert_wall,
        insert_height - floor_thickness + 1
      ]);
  }}
}}

drawer_insert();
"""


def _resolved_insert(c) -> str:
    section_width = _safe_dimension(c.cabinet_width / c.drawers_x, 1)
    section_height = _safe_dimension(c.cabinet_height / c.drawers_y, 1)
    section_depth = _safe_dimension(c.cabinet_depth, 1)
    insert_width = _safe_dimension(
        section_width - c.fit_clearance,
        c.insert_wall_thickness * 2 + 1,
    )
    insert_height = _safe_dimension(
        section_height - c.fit_clearance,
        c.insert_wall_thickness * 2 + 1,
    )
    insert_depth = _safe_dimension(
        section_depth - c.fit_clearance,
        c.floor_thickness + 1,
    )
    inner_width = _safe_dimension(insert_width - 2 * c.insert_wall_thickness, 1)
    inner_depth = _safe_dimension(insert_depth - 2 * c.insert_wall_thickness, 1)

    return f"""// StorageMaker - Drawer Insert
// Generated by StorageMaker

module drawer_insert() {{
  difference() {{
    cube([{insert_width}, {insert_depth}, {insert_height}]);
    translate([{c.insert_wall_thickness}, {c.insert_wall_thickness}, {c.floor_thickness}])
      cube([{inner_width}, {inner_depth}, {insert_height - c.floor_thickness + 1}]);
  }}
}}

drawer_insert();
"""


def _safe_dimension(value: float, minimum: float) -> float:
    return max(value, minimum)